name: 'fintech_plg'
version: '1.0.0'

profile: 'fintech_plg_duckdb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

seeds:
  fintech_plg:
    events:
      +column_types:
        user_id: varchar
        event_type: varchar
        event_time: timestamp
    transactions:
      +column_types:
        transaction_id: varchar
        user_id: varchar
        amount: double
        timestamp: timestamp
    users:
      +column_types:  
        user_id: varchar
        signup_date: timestamp
        plan_type: varchar
        

models:
  fintech_plg:
    staging:
      +materialized: view
      +tags: ["staging"]
    
    core:
      +materialized: view
      +tags: ["core"]
    
    marts:
      +materialized: table
      +tags: ["marts"]

# Configuring snapshots
snapshots:
  fintech_plg:
    +schema: snapshots
