version: 2

models:

  - name: core_user_activity
    description: "User-level activity and revenue summary."
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('dim_users')
              field: user_id

  - name: dim_users
    description: "Current-state canonical user dimension."
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: plan_type
        tests:
          - accepted_values:
              values: ['free', 'premium', 'enterprise']

  - name: fact_events
    description: "Atomic event fact table (one row per event)."
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - relationships:
              to: ref('dim_users')
              field: user_id

  - name: fact_events_with_plan
    description: "Event fact enriched with plan active at event time using snapshot validity windows."
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('fact_events')
              field: event_id

      - name: user_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id

      - name: plan_type
        description: "Plan active at the time the event occurred (temporal join)."
  
  - name: fact_events_with_amount
    description: "Event fact enriched with amount (if event is a transaction)."
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('fact_events')
              field: event_id
      - name: amount
        tests:
          - not_null