version: 2

models:

  - name: stg_users
    description: "Staging model that cleans and standardizes user records."
    columns:
      - name: user_id
        description: "Raw user identifier from source."
        tests:
          - not_null

      - name: user_id_clean
        description: "Canonical lowercase trimmed user id used for joins."
        tests:
          - not_null

      - name: signup_date
        description: "Parsed signup date, null if invalid in source."
        tests:
          - not_null

      - name: plan_type_clean
        description: "Normalized plan type (free/premium/enterprise)."
        tests:
          - accepted_values:
              values: ['free', 'premium', 'enterprise']

      - name: is_bad_signup_date
        description: "Flag when signup_date could not be cast properly."

  - name: stg_transactions
    description: "Staging model for transactions. Handles dupes, malformed timestamps, orphan users."
    columns:
      - name: transaction_id
        description: "Raw transaction identifier (may contain duplicates in source)."
        tests:
          - not_null

      - name: user_id_clean
        description: "Normalized user id for joining to users."
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id_clean
              severity: warn

      - name: transaction_time
        description: "Parsed transaction timestamp."
        tests:
          - not_null

      - name: is_duplicate_transaction
        description: "Flag indicating a dropped duplicate transaction."

      - name: is_bad_timestamp
        description: "Flag for failed timestamp parsing."

  - name: stg_events
    description: "Staging model for user event activity, standardizing event types & timestamps."
    columns:
      - name: user_id_clean
        description: "Normalized user id for joining to users."
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id_clean
              severity: warn

      - name: event_type
        description: "Normalized event category."
        tests:
          - not_null

      - name: event_time
        description: "Parsed event timestamp."
        tests:
          - not_null

      - name: is_bad_timestamp
        description: "Flag when event_time failed parsing."
